// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtgQHcoNW4plBnnvsCFTSGX-IhjNYzLNI',
    appId: '1:755241630226:web:df0819ec02d1700788b6cb',
    messagingSenderId: '755241630226',
    projectId: 'your-online-bookshelf-7adba',
    authDomain: 'your-online-bookshelf-7adba.firebaseapp.com',
    storageBucket: 'your-online-bookshelf-7adba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHD0DFvE_1JUXbskstkRjDbYupSsp57KU',
    appId: '1:755241630226:android:c360c69279cd9ce788b6cb',
    messagingSenderId: '755241630226',
    projectId: 'your-online-bookshelf-7adba',
    storageBucket: 'your-online-bookshelf-7adba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhtLaU0TXh3FNQkvnDSJpVMOCFSWkVIa0',
    appId: '1:755241630226:ios:e49fc4133789ef7188b6cb',
    messagingSenderId: '755241630226',
    projectId: 'your-online-bookshelf-7adba',
    storageBucket: 'your-online-bookshelf-7adba.firebasestorage.app',
    iosBundleId: 'com.example.cuoiKy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhtLaU0TXh3FNQkvnDSJpVMOCFSWkVIa0',
    appId: '1:755241630226:ios:e49fc4133789ef7188b6cb',
    messagingSenderId: '755241630226',
    projectId: 'your-online-bookshelf-7adba',
    storageBucket: 'your-online-bookshelf-7adba.firebasestorage.app',
    iosBundleId: 'com.example.cuoiKy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtgQHcoNW4plBnnvsCFTSGX-IhjNYzLNI',
    appId: '1:755241630226:web:746dff0003752a8c88b6cb',
    messagingSenderId: '755241630226',
    projectId: 'your-online-bookshelf-7adba',
    authDomain: 'your-online-bookshelf-7adba.firebaseapp.com',
    storageBucket: 'your-online-bookshelf-7adba.firebasestorage.app',
  );
}
